name: abstracta_repository
description: Abstracta Repository
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.10.1
  freezed_annotation: ^2.4.1
  local_storage_service:
    path: ../local_storage_service
  gemini_service:
    path: ../gemini_service

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
  freezed: ^2.4.5
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

